[project]
name = "pytankwar"
version = "0.1.0"
dependencies = ["pygame","flask","requests"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"tankwar.drawer.images" = ["*.png"]